// Portfolio content: one entry per card, in display order.
//
// year       shown on the card; "" hides it
// cover      index of the media item shown on the card (default 0)
// coverPos   optional crop position for the card image, e.g. "50% 30%"
//
// media items:
//   { img: "img/<id>/01", w, h, caption }       photo in this repo (01.webp, 01-md.webp, 01-sm.webp)
//   { video: "img/<id>/v05", poster: "img/<id>/v05-poster" }   video (v05.webm and v05.mp4)
//
// Add photos with: python3 tools/add_photos.py <id> photo1.jpg photo2.heic ...

window.PROJECTS = [
  {
    id: "biology-playing-cards",
    title: "3D printed playing cards",
    year: "2026",
    description: "A 54-card deck made for multi-colour 3D printing, with biology-themed suits: protein, DNA, metabolites and RNA. A script converts any themed design to printable card models, with multi-color printing creating patterns within cards. Printable in-place as a deck with spacers from a different plastic, separating after printing.",
    media: [
      { img: "img/biology-playing-cards/01", w: 1497, h: 2000 },
      { img: "img/biology-playing-cards/02", w: 1497, h: 2000 },
      { img: "img/biology-playing-cards/03", w: 2000, h: 1497 },
      { img: "img/biology-playing-cards/04", w: 2000, h: 1497 },
      { img: "img/biology-playing-cards/05", w: 1497, h: 2000, caption: "On display at RoboCon NJ 2026" },
    ],
  },
  {
    id: "laser-engraved-portraits",
    title: "Laser-engraved portraits",
    year: "2023–2026",
    description: "Photographs engraved into wood: A workflow converting photos to a stacked wooden ornament for hanging using laser cutting and engraving.",
    media: [
      { img: "img/laser-engraved-portraits/01", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/02", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/03", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/04", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/05", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/06", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/07", w: 1500, h: 2000 },
      { img: "img/laser-engraved-portraits/08", w: 1497, h: 2000 },
    ],
  },
  {
    id: "alien-with-bowl",
    title: "Turned ashtray with a companion Martian.",
    year: "2026",
    coverPos: "50% 72%",
    description: "A small wooden bowl manually turned on the lathe, held by a bespoke fitted 3D-printed Martian generated with generative design.",
    media: [
      { img: "img/alien-with-bowl/01", w: 1497, h: 2000 },
      { img: "img/alien-with-bowl/02", w: 2000, h: 1497, caption: "On the lathe" },
    ],
  },
  {
    id: "stamps",
    title: "Stamps",
    year: "2025–2026",
    description: "Custom-made stamps. A product of a digitally assisted crafts workshop. Digital designs converted to a 3D-printed molde, cast with silicone rubber.",
    media: [
      { img: "img/stamps/01", w: 1506, h: 2000 },
      { img: "img/stamps/02", w: 1125, h: 2000 , caption: "On display at RoboCon NJ 2026"},
    ],
  },
  {
    id: "laser-cut-tiles",
    title: "Laser-cut pattern tiles",
    year: "2023–2025",
    description: "Wooden tiles cut with a repeating musical pattern using a laser cutter. Epoxy incorporated into design for a stained-glass look.",
    media: [
      { img: "img/laser-cut-tiles/01", w: 1497, h: 2000 },
      { img: "img/laser-cut-tiles/02", w: 1500, h: 2000 },
      { img: "img/laser-cut-tiles/03", w: 1500, h: 2000 },
    ],
  },
  {
    id: "small-laser-pieces",
    title: "Small laser-cut pieces",
    year: "2023–2025",
    description: "Cut and engraved wood: engraved animal tokens, a batch of small figures and cartoon-portrait tags.",
    media: [
      { img: "img/small-laser-pieces/01", w: 1497, h: 2000 },
      { img: "img/small-laser-pieces/02", w: 1875, h: 2000 },
      { img: "img/small-laser-pieces/03", w: 1497, h: 2000 },
    ],
  },
  {
    id: "netilah",
    title: "Netilah",
    year: "2025",
    coverPos: "30% 50%",
    description: "A pot hangs on its own stream of water, pouring over a pair of hands. Collaboration with Leena Bagawade, sculpting, Genyuan Hu, ceramics. UV resin and epoxy resin modeled to capture a dynamic flow.",
    media: [
      { img: "img/netilah/01", w: 2000, h: 1500 },
      { img: "img/netilah/02", w: 1500, h: 2000 , caption: "On display at the 2025 Plainsboro Art Group exhibition."},
    ],
  },
  {
    id: "wooden-spheres",
    title: "Wooden spheres",
    year: "2024–2026",
    coverPos: "50% 60%",
    description: "Machine-created Balls cut from wood and epoxy resin. Original design by FraensEngineering, modified version by me.",
    media: [
      { img: "img/wooden-spheres/01", w: 1497, h: 2000 },
      { img: "img/wooden-spheres/02", w: 1125, h: 2000 },
      { img: "img/wooden-spheres/03", w: 1497, h: 2000 },
      { img: "img/wooden-spheres/04", w: 2000, h: 913, caption: "On display at RoboCon NJ 2026" },
    ],
  },
  {
    id: "painted-ganesha",
    title: "Painted Ganesha",
    year: "2025",
    coverPos: "50% 22%",
    description: "A Ganesha statue, painted by hand.",
    media: [
      { img: "img/painted-ganesha/01", w: 1497, h: 2000 },
    ],
  },
  {
    id: "astronaut-spheres",
    title: "Astronaut spheres",
    year: "2025",
    description: "A strange planet. Generative design 3D-printed scene, with attached moon self-illuminating on magnetic attachment.",
    media: [
      { img: "img/astronaut-spheres/01", w: 2000, h: 1497 },
      { img: "img/astronaut-spheres/02", w: 2000, h: 1497 },
    ],
  },
  {
    id: "framed-mountain-coast",
    title: "Mountain coast in a frame",
    year: "2025",
    description: "Island in a mirror. A hybrid generative design and clay sculpted terrain, UV and epoxy resin water.",
    media: [
      { img: "img/framed-mountain-coast/01", w: 2000, h: 1497 },
      { img: "img/framed-mountain-coast/02", w: 1497, h: 2000 },
    ],
  },
  {
    id: "painted-birds",
    title: "Painted birds",
    year: "2025",
    description: "3D-printed Bird figures painted by hand and mounted on branches and bases. Taxidermy models courtsey of RISD Nature Lab.",
    media: [
      { img: "img/painted-birds/01", w: 1497, h: 2000 },
      { img: "img/painted-birds/02", w: 2000, h: 1497 },
    ],
  },
  {
    id: "donation-box-turtles",
    title: "Turtles for a donation box",
    year: "2025",
    description: "3D-printed Eastern box turtle hand painted for a donation box at The Watershed Institute visitor center. Taxidermy model courtsey of RISD Nature Lab.",
    media: [
      { img: "img/donation-box-turtles/01", w: 2000, h: 1497 },
      { img: "img/donation-box-turtles/02", w: 1497, h: 2000 },
      { img: "img/donation-box-turtles/03", w: 2000, h: 1497 },
    ],
  },
  {
    id: "cloud-dome",
    title: "Cloud dome",
    year: "2025",
    description: "A clear resin dome with blue and white clouds suspended inside.",
    media: [
      { img: "img/cloud-dome/01", w: 2000, h: 1497 },
    ],
  },
  {
    id: "wooden-and-sculpted-rings",
    title: "Wooden and sculpted rings",
    year: "2024–2025",
    description: "Hand shaped wooden rings, cast resin rings and generative design 3D printed rings.",
    media: [
      { img: "img/wooden-and-sculpted-rings/01", w: 2000, h: 1497 },
      { img: "img/wooden-and-sculpted-rings/02", w: 2000, h: 1497 },
      { img: "img/wooden-and-sculpted-rings/03", w: 2000, h: 1497 },
      { img: "img/wooden-and-sculpted-rings/04", w: 1497, h: 2000 },
    ],
  },
  {
    id: "skull-staff",
    title: "Skull staff",
    year: "2024",
    description: "An animal skull on a twisted staff dressed for the afterlife. Materials self sourced from The Watershed Institute grounds.",
    media: [
      { img: "img/skull-staff/01", w: 1497, h: 2000 },
      { img: "img/skull-staff/02", w: 1497, h: 2000 },
      { img: "img/skull-staff/03", w: 1497, h: 2000, caption: "At a craft fair" },
    ],
  },
  {
    id: "great-wave-driftwood",
    title: "Great Wave driftwood",
    year: "2024",
    description: "Wood cambium hand painted as a crushing wave.",
    media: [
      { img: "img/great-wave-driftwood/01", w: 2000, h: 1497 },
      { img: "img/great-wave-driftwood/02", w: 2000, h: 1497, caption: "At The Watershed Institute winter market." },
    ],
  },
  {
    id: "violins-with-mice",
    title: "Violins with sleeping cat",
    year: "2024",
    description: "3D-printed string instruments, cozy and perfect for a cat nap.",
    media: [
      { img: "img/violins-with-mice/01", w: 1497, h: 2000 },
      { img: "img/violins-with-mice/02", w: 2000, h: 1497 },
    ],
  },
  {
    id: "live-edge-stands",
    title: "Live-edge stands and cedar pieces",
    year: "2024",
    description: "Decorative stands for a rustic elegance donor event at The Watershed Institute.",
    media: [
      { img: "img/live-edge-stands/01", w: 2000, h: 1497 },
      { img: "img/live-edge-stands/02", w: 2000, h: 1497 },
      { img: "img/live-edge-stands/03", w: 2000, h: 1497 },
    ],
  },
  {
    id: "wood-rings-splash",
    title: "Wood rings with a resin splash",
    year: "2024",
    description: "Lathe-turned wavy wood with UV and epoxy resin water scene.",
    media: [
      { img: "img/wood-rings-splash/01", w: 2000, h: 1500 },
    ],
  },
  {
    id: "coffee-bean-alien",
    title: "Coffee-bean alien",
    year: "2023",
    description: "A coffee Martian set in epoxy resin, made for the Grover Mill's Coffee Company.",
    media: [
      { img: "img/coffee-bean-alien/01", w: 1500, h: 2000 },
    ],
  },
  {
    id: "lighthouse-diorama",
    title: "Journey",
    year: "2023",
    description: "A whittled lighthouse on a rocky shore, wood, rocks and epoxy resin.",
    media: [
      { img: "img/lighthouse-diorama/01", w: 2000, h: 1500 },
      { img: "img/lighthouse-diorama/02", w: 900, h: 1200, caption: "On display at the 2023 Plainsboro Art Group exhibition." },
    ],
  },
  {
    id: "tree-of-life",
    title: "New old growth",
    year: "2022",
    description: "An dead tree hosts new symbolic life. Hand shaped, epoxy resin cast.",
    media: [
      { img: "img/tree-of-life/01", w: 1497, h: 2000 },
      { img: "img/tree-of-life/02", w: 2000, h: 1500 },
    ],
  },
  {
    id: "spilled-wine-glass",
    title: "Spilled wine glass",
    year: "2022",
    description: "Cold ocean spills from a tilted glass.",
    media: [
      { img: "img/spilled-wine-glass/01", w: 1496, h: 2000 },
      { img: "img/spilled-wine-glass/02", w: 1440, h: 1080, caption: "Pouring the resin" },
    ],
  },
  {
    id: "charred-wood-coast",
    title: "Charred wood coastline",
    year: "2022",
    description: "Charred wood with orange-filled cracks, meeting a teal resin sea with white surf.",
    media: [
      { img: "img/charred-wood-coast/01", w: 2000, h: 1125 },
      { img: "img/charred-wood-coast/02", w: 2000, h: 1500 },
    ],
  },
  {
    id: "resin-rings",
    title: "Resin rings",
    year: "2022",
    description: "Swirled and marbled resin rings. Some glow in the dark.",
    media: [
      { img: "img/resin-rings/01", w: 2000, h: 1502 },
      { img: "img/resin-rings/02", w: 2000, h: 1502 },
      { img: "img/resin-rings/03", w: 2000, h: 1502 },
      { img: "img/resin-rings/04", w: 2000, h: 1502 },
      { img: "img/resin-rings/05", w: 2000, h: 1502 },
      { img: "img/resin-rings/06", w: 1502, h: 2000 },
    ],
  },
  {
    id: "resin-side-table",
    title: "Resin side table",
    year: "2022",
    coverPos: "50% 80%",
    description: "A round tabletop with agate slices set in red and teal resin.",
    media: [
      { img: "img/resin-side-table/01", w: 1200, h: 1600 },
    ],
  },
  {
    id: "resin-castings-2020",
    title: "Resin keychains and castings",
    year: "2020",
    description: "Keychains, a ring and a bangle, a clear block with embedded plants, and a resin-and-grit cylinder.",
    media: [
      { img: "img/resin-castings-2020/01", w: 2000, h: 1500 },
      { img: "img/resin-castings-2020/02", w: 2000, h: 1500 },
      { img: "img/resin-castings-2020/03", w: 1500, h: 2000 },
      { img: "img/resin-castings-2020/04", w: 2000, h: 1500 },
      { video: "img/resin-castings-2020/v05", poster: "img/resin-castings-2020/v05-poster", w: 1920, h: 1080 },
      { img: "img/resin-castings-2020/06", w: 1500, h: 2000 },
      { video: "img/resin-castings-2020/v07", poster: "img/resin-castings-2020/v07-poster", w: 1080, h: 1920 },
    ],
  },
  {
    id: "embroidered-sword-tattoo",
    title: "Embroidered sword tattoo",
    year: "2011",
    cover: 9,
    description: "Replicating a back tattoo in machine embroidery: the original, the design, and the stitching.",
    media: [
      { img: "img/embroidered-sword-tattoo/01", w: 214, h: 314, caption: "The original tattoo" },
      { img: "img/embroidered-sword-tattoo/02", w: 1036, h: 2000, caption: "The design" },
      { img: "img/embroidered-sword-tattoo/03", w: 634, h: 790, caption: "Design and tattoo side by side" },
      { img: "img/embroidered-sword-tattoo/04", w: 1280, h: 1600, caption: "Design sheet" },
      { img: "img/embroidered-sword-tattoo/05", w: 2000, h: 1500, caption: "Setting the frame with foam" },
      { img: "img/embroidered-sword-tattoo/06", w: 2000, h: 1500, caption: "Setting the frame with foam" },
      { img: "img/embroidered-sword-tattoo/07", w: 2000, h: 1500, caption: "Embroidering" },
      { img: "img/embroidered-sword-tattoo/08", w: 2000, h: 1500, caption: "Embroidering" },
      { img: "img/embroidered-sword-tattoo/09", w: 2000, h: 1500, caption: "Midway" },
      { img: "img/embroidered-sword-tattoo/10", w: 2000, h: 1500, caption: "Final" },
    ],
  },
  {
    id: "embroidered-checkers-board",
    title: "Embroidered checkers board",
    year: "2011",
    cover: 2,
    description: "A travel checkers board in machine embroidery. It folds into a pouch that holds the pieces.",
    media: [
      { img: "img/embroidered-checkers-board/01", w: 1600, h: 1280, caption: "Design" },
      { img: "img/embroidered-checkers-board/02", w: 2000, h: 1500, caption: "Work" },
      { img: "img/embroidered-checkers-board/03", w: 960, h: 1280, caption: "Ready to play" },
      { img: "img/embroidered-checkers-board/04", w: 960, h: 1280, caption: "Made to store" },
      { img: "img/embroidered-checkers-board/05", w: 960, h: 1280, caption: "Back side message" },
    ],
  },
  {
    id: "machine-embroidery",
    title: "Machine embroidery",
    year: "2011–2014",
    cover: 6,
    description: "Assorted machine embroidery, from design to manufacture: patches, logos and portraits.",
    media: [
      { img: "img/machine-embroidery/01", w: 536, h: 800 },
      { img: "img/machine-embroidery/02", w: 536, h: 800 },
      { img: "img/machine-embroidery/03", w: 600, h: 402 },
      { img: "img/machine-embroidery/04", w: 600, h: 402 },
      { img: "img/machine-embroidery/05", w: 1963, h: 1963, caption: "Design" },
      { img: "img/machine-embroidery/06", w: 2000, h: 2000, caption: "Stitch preview" },
      { img: "img/machine-embroidery/07", w: 1494, h: 2000, caption: "Finished patch" },
      { img: "img/machine-embroidery/08", w: 1760, h: 1280, caption: "Design sheet" },
      { img: "img/machine-embroidery/09", w: 960, h: 1280, caption: "On a backpack" },
      { img: "img/machine-embroidery/10", w: 1455, h: 2000, caption: "Design sheet" },
      { img: "img/machine-embroidery/11", w: 960, h: 1280, caption: "Finished patches" },
      { img: "img/machine-embroidery/12", w: 1494, h: 2000 },
      { img: "img/machine-embroidery/13", w: 960, h: 1280 },
      { img: "img/machine-embroidery/14", w: 2000, h: 1852 },
      { img: "img/machine-embroidery/15", w: 1280, h: 1760 },
      { img: "img/machine-embroidery/16", w: 1280, h: 1760 },
      { img: "img/machine-embroidery/17", w: 1280, h: 1760 },
      { img: "img/machine-embroidery/18", w: 1760, h: 1280 },
      { img: "img/machine-embroidery/19", w: 1280, h: 1600 },
    ],
  },
  {
    id: "photography",
    title: "Photography",
    year: "2010–2014",
    description: "Selected photographs.",
    media: [
      { img: "img/photography/01", w: 1333, h: 2000 },
      { img: "img/photography/02", w: 2000, h: 1333 },
      { img: "img/photography/03", w: 2000, h: 1333 },
      { img: "img/photography/04", w: 2000, h: 1333 },
      { img: "img/photography/05", w: 2000, h: 1333 },
      { img: "img/photography/06", w: 2000, h: 1333 },
      { img: "img/photography/07", w: 2000, h: 1500 },
      { img: "img/photography/08", w: 1333, h: 2000 },
      { img: "img/photography/09", w: 2000, h: 1333 },
      { img: "img/photography/10", w: 2000, h: 1333 },
      { img: "img/photography/11", w: 2000, h: 1333 },
      { img: "img/photography/12", w: 2000, h: 1333 },
      { img: "img/photography/13", w: 1333, h: 2000 },
      { img: "img/photography/14", w: 2000, h: 1333 },
      { img: "img/photography/15", w: 2000, h: 1333 },
      { img: "img/photography/16", w: 2000, h: 1333 },
      { img: "img/photography/17", w: 2000, h: 1333 },
      { img: "img/photography/18", w: 1333, h: 2000 },
      { img: "img/photography/19", w: 2000, h: 1333 },
      { img: "img/photography/20", w: 2000, h: 1333 },
      { img: "img/photography/21", w: 2000, h: 1333 },
      { img: "img/photography/22", w: 2000, h: 1333 },
      { img: "img/photography/23", w: 2000, h: 1333 },
      { img: "img/photography/24", w: 2000, h: 1333 },
      { img: "img/photography/25", w: 2000, h: 1333 },
      { img: "img/photography/26", w: 2000, h: 1123 },
      { img: "img/photography/27", w: 768, h: 576 },
      { img: "img/photography/28", w: 640, h: 480 },
      { img: "img/photography/29", w: 806, h: 374 },
      { img: "img/photography/30", w: 2000, h: 1125 },
      { img: "img/photography/31", w: 1125, h: 2000 },
      { img: "img/photography/32", w: 2000, h: 1125 },
      { img: "img/photography/33", w: 1125, h: 2000 },
      { img: "img/photography/34", w: 2000, h: 1125 },
      { img: "img/photography/35", w: 2000, h: 1125 },
      { img: "img/photography/36", w: 2000, h: 1125 },
      { img: "img/photography/37", w: 1125, h: 2000 },
      { img: "img/photography/38", w: 2000, h: 1125 },
      { img: "img/photography/39", w: 2000, h: 1125 },
      { img: "img/photography/40", w: 2000, h: 1125 },
      { img: "img/photography/41", w: 2000, h: 1125 },
      { img: "img/photography/42", w: 2000, h: 1125 },
      { img: "img/photography/43", w: 1200, h: 2000 },
      { img: "img/photography/44", w: 768, h: 1280 },
      { img: "img/photography/45", w: 1200, h: 2000 },
      { img: "img/photography/46", w: 2000, h: 1200 },
      { img: "img/photography/47", w: 2000, h: 1200 },
      { img: "img/photography/48", w: 2000, h: 1200 },
    ],
  },
];
